/**
 * Centralized Error Codes
 * All application errors should use these codes for consistency
 * Format: DOMAIN_XXX where XXX is a numeric identifier
 */

export const ErrorCodes = {
    // Authentication errors (AUTH_001 - AUTH_099)
    AUTH_INVALID_CREDENTIALS: 'AUTH_001',
    AUTH_TOKEN_EXPIRED: 'AUTH_002',
    AUTH_TOKEN_INVALID: 'AUTH_003',
    AUTH_TOKEN_MISSING: 'AUTH_004',
    AUTH_REFRESH_TOKEN_INVALID: 'AUTH_005',
    AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_006',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH_007',
    AUTH_ACCOUNT_LOCKED: 'AUTH_008',
    AUTH_EMAIL_NOT_VERIFIED: 'AUTH_009',
    AUTH_SESSION_EXPIRED: 'AUTH_010',

    // Authorization errors (AUTHZ_001 - AUTHZ_099)
    AUTHZ_FORBIDDEN: 'AUTHZ_001',
    AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_002',
    AUTHZ_ROLE_REQUIRED: 'AUTHZ_003',

    // User errors (USER_001 - USER_099)
    USER_NOT_FOUND: 'USER_001',
    USER_EMAIL_EXISTS: 'USER_002',
    USER_INVALID_EMAIL: 'USER_003',
    USER_INVALID_PASSWORD: 'USER_004',
    USER_PASSWORD_MISMATCH: 'USER_005',
    USER_DEACTIVATED: 'USER_006',
    USER_PROFILE_NOT_FOUND: 'USER_007',

    // Owner errors (OWNER_001 - OWNER_099)
    OWNER_NOT_FOUND: 'OWNER_001',
    OWNER_PROFILE_EXISTS: 'OWNER_002',
    OWNER_GST_EXISTS: 'OWNER_003',
    OWNER_NOT_VERIFIED: 'OWNER_004',

    // Customer errors (CUSTOMER_001 - CUSTOMER_099)
    CUSTOMER_NOT_FOUND: 'CUSTOMER_001',
    CUSTOMER_PROFILE_EXISTS: 'CUSTOMER_002',

    // Banquet errors (BANQUET_001 - BANQUET_099)
    BANQUET_NOT_FOUND: 'BANQUET_001',
    BANQUET_NAME_EXISTS: 'BANQUET_002',
    BANQUET_CAPACITY_EXCEEDED: 'BANQUET_003',
    BANQUET_UNAVAILABLE: 'BANQUET_004',
    BANQUET_INVALID_DATES: 'BANQUET_005',

    // Booking errors (BOOKING_001 - BOOKING_099)
    BOOKING_NOT_FOUND: 'BOOKING_001',
    BOOKING_CONFLICT: 'BOOKING_002',
    BOOKING_CANCELLED: 'BOOKING_003',
    BOOKING_INVALID_DATES: 'BOOKING_004',
    BOOKING_PAST_DATE: 'BOOKING_005',
    BOOKING_CAPACITY_EXCEEDED: 'BOOKING_006',

    // Validation errors (VALIDATION_001 - VALIDATION_099)
    VALIDATION_FAILED: 'VALIDATION_001',
    VALIDATION_REQUIRED_FIELD: 'VALIDATION_002',
    VALIDATION_INVALID_FORMAT: 'VALIDATION_003',
    VALIDATION_MIN_LENGTH: 'VALIDATION_004',
    VALIDATION_MAX_LENGTH: 'VALIDATION_005',

    // Database errors (DB_001 - DB_099)
    DB_CONNECTION_FAILED: 'DB_001',
    DB_QUERY_FAILED: 'DB_002',
    DB_DUPLICATE_KEY: 'DB_003',
    DB_TRANSACTION_FAILED: 'DB_004',

    // General errors (GENERAL_001 - GENERAL_099)
    INTERNAL_ERROR: 'GENERAL_001',
    NOT_FOUND: 'GENERAL_002',
    BAD_REQUEST: 'GENERAL_003',
    CONFLICT: 'GENERAL_004',
    SERVICE_UNAVAILABLE: 'GENERAL_005',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
